name: rewards-cron
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://stake-new.narentines.com/api/crons/rewards' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
